### PR TITLE
Fix most of the shellcheck issues

### LINKED ISSUE #255: Install script cannot handle space in `$WP_DIRECTORY`
The install script contains various parts that cannot handle spaces in variable `$WP_DIRECTORY` correctly.

For example:

    echo "WP_BOX='$WP_DIRECTORY' . $SP_PATH/bin/launcher.sh" >> $WP_DIRECTORY/box-run.sh

will try to write to file or directory ending at the first space in the variable.  In addition, if `$WP_DIRECTORY` contains single quote mark, then the remaining part after the first space of the `$WP_DIRECTORY` will be executed instead of launcher.sh as designed.

I think the best way to handle issues like this is to do something like this:

    SHELL_ENCODED_WP_DIRECTORY="$(printf "%s" "$WP_DIRECTORY" | sed "s/'/'\x22'\x22'/")"
    SHELL_ENCODED_SP_PATH="$(printf "%s" "$SP_PATH" | sed "s/'/'\x22'\x22'/")"
    echo "WP_BOX='$SHELL_ENCODED_WP_DIRECTORY'" source '"'$SHELL_ENCODED_SP_PATH/bin/launcher.sh'"' >> "$WP_DIRECTORY/box-run.sh"

Similar tweaks would be needed for other parts that generate new shell scripts. Other parts can just use double quotes around the variables. I also used `source` instead of `.` above to make it more readable. You already have `bash` shebang so you might as well use more readable `bash` features.

### PR DESCRIPTION
**Pull request by gromain**
## 📝 Description
Solve the shellcheck issues. This should solve some issues in rare cases.
Closes #255 and #246 (partially).
Not yet fully tested

### CODE REVIEW

**Comment by gromain** [comment]
There's an issue, please don't use yet.

**Comment by gromain** [comment]
Typo fixed

**Comment by gromain** [comment]
There, this should work as expected.

Also fixed an issue [here](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/main/files/builds/stable-branch/bin/install.sh#L1135) where the label was checked instead of the proper value. This prevented Fusion from being started even if the tick box was checked by the user.

**Comment by cryinkfly** [comment]
Hey @gromain, thanks for your help! :+1: 

>  Not yet fully tested

If you have tested your code now?

**Comment by cryinkfly** [comment]
@gromain  So I have checked this itself. :+1:  Nice work!!! :100:

**Comment by cryinkfly** [comment]
@gromain The only problem was the locale.sh file. Then the wget can't read the links correctly, but with the older version of locale.sh it works.

**Pull request merged**
