### PR TITLE
Add a command to use an older version of Fusion 360 until #319 is fixed

### PR DESCRIPTION
**Pull request by dumbnerd08**
## 📝 Description

Adds a link to a tested version of Fusion 360 for Linux that uses an older version of Fusion 360 from the Wayback Machine. This resolves issue #319 and PR #322. Translations for other languages have been verified. New documentation has been integrated correctly into the readme.

## 📑 Context

This change gives Fusion 360 for Linux real function until we can fix issue #319. It solves the welcome browser not opening because it uses and older version for Fusion 360.

## ✅ Checklist:

- [ ] Updated tests for this change.
- [x] Tested the changes locally.
- [x] Updated documentation.
- [ ] Change version number.
- [ ] Change the time and date.

### 📸 Screenshots (if available)

image

### CODE REVIEW

**Comment by paukstelis** [comment]
Testing this out, but unfortunately the link from web.archive.org never completes downloading via curl. `Read error at byte 983315533....`

**Comment by dumbnerd08** [comment]
> Testing this out, but unfortunately the link from web.archive.org never completes downloading via curl. `Read error at byte 983315533....`

It seems that alextrical, the original creator of the fork that includes the older version of fusion 360, has set the number of tries for the wget command to infinite. I will try to find a source for the older version. In the meantime, please try running `wget -T 15 -t 0 -N -c 'https://web.archive.org/web/20230317210714id_/https://dl.appstreaming.autodesk.com/production/installers/Fusion 360 Admin Install.exe' -O Fusion360installer.exe` like what is found in alextrical's fork.

**Comment by kcneato** [comment]
Hi, i cant get this to run, i get the same errors. Both when trying to make a "native" install and when running flatpack pacage with bottles. In bottles i still get the same error as after the previus uppdate. Is there something special install method to do in bootles to makes this to work, install from the old source?

**Comment by dumbnerd08** [comment]
> Hi, i cant get this to run, i get the same errors. Both when trying to make a "native" install and when running flatpack pacage with bottles. In bottles i still get the same error as after the previus uppdate. Is there something special install method to do in bootles to makes this to work, install from the old source?
> 
> /edit 
> 
> sorry realised that this is not yet merged to the main code!
> 

Would you mind testing the fork mentioned in the latest README commit and see if it downloads and installs for you?

**Comment by kcneato** [comment]
> > Hi, i cant get this to run, i get the same errors. Both when trying to make a "native" install and when running flatpack pacage with bottles. In bottles i still get the same error as after the previus uppdate. Is there something special install method to do in bootles to makes this to work, install from the old source?
> > /edit
> > sorry realised that this is not yet merged to the main code!
> 
> Would you mind testing the fork mentioned in the latest README commit and see if it downloads and installs for you?
> 
> Edit: the bottles version has not yet been patched. As far as I know, this project is unrelated to the bottles version.

Hi, it actually installs, but I have been using bottles before only. I dont figure out actually how to get the wine startup script to work to be honest, cant make it to work with the documentation given on the main page, so my lack of skills here on how to make a startup script...

**Comment by kcneato** [comment]
May i ask, dow do you fix the issue of common known error? And go on from there?
  cannot create directory ‘/tmp/fusion360/logs’: File exists


I am running latest linux mint, and have this issue forever. This is why i only mammaged to get this running in Bottles :)

**Comment by paukstelis** [comment]
> May i ask, dow do you fix the issue of common known error? And go on from there? cannot create directory ‘/tmp/fusion360/logs’: File exists
> 
> I am running latest linux mint, and have this issue forever. This is why i only mammaged to get this running in Bottles :)

I think there are lot of inconsistencies in how this script operates with different distros.
Finding out which script was needed to actually launch (box-run.sh) took a while. One would _think_ that /bin/launcher.sh would work....

**Comment by kcneato** [comment]
Ok thanks. 

Yeah, dont get it to work. 

However, i do get it to work with bootles now. Very strange but yes it works now again! Not always but one has to fiddle little with the settings in the bootles!!


Screenshot from 2023-04-30 00-13-16

**Comment by monte-monte** [comment]
@kcneato you mean you were able to sign in? Or did it just launched with saved credentials without you signing in?

**Comment by kcneato** [comment]
> @kcneato you mean you were able to sign in? Or did it just launched with saved credentials without you signing in?

Able to sign in from scratch. I did fet the sign in screen the first login now, aable to login, thereafter the login dont come again as you know. Honestly i dont ubderstand why it worked. you can see my settings, they are attached. i did a time shift jump back two weeks. I had saved it there after a very clean reinstall of Mint. 

So yea, i get the login screen, exactly as you get at windows (i am running in vm player the last weeks so i know how the new login experience works)

**Comment by monte-monte** [comment]
> I did get the sign in screen the first login now, anle to login, thereafter the login dont come again as you know.
Do you mean that login screen opened in browser or in Fusion?
In particular, did you click on this button and did browser open after?
image

**Comment by kcneato** [comment]
> > I did get the sign in screen the first login now, anle to login, thereafter the login dont come again as you know.
> > Do you mean that login screen opened in browser or in Fusion?
> > In particular, did you click on this button and did browser open after?
> > image

Hi, yes i clicked this link, and then Bottles appeared to open the inbuilt browser yes indeed where i need to login. Then logged in with my fusion credentials in the browser. Then it login (as said, to me the same experience as when i run the "new" fusion at a windows 11 machine) 

I dont get the login window now when i am opening it again, only the first time. 

(I can also say that i tried to save the bottle itself, like a full backup as i wanted to try if i can save the backup and login again. However that dint work, when reinstalling the bottle again and trying to run fusion from that saved bottle, absolutely nothing happens, dont start and not even an error message)

**Comment by monte-monte** [comment]
@kcneato That's interesting, because it's exactly what is supposed to happen, but for some reason does not. It would be great if you could find out what exactly did you change.

**Comment by human664** [comment]
dxvk nvapi is the only thing i have different aside from os (manjaro) and no such luck
2023-04-30-124450_606x320_scrot

**Comment by Bbenno-UX** [comment]
Can verfify that it works on a freshly installed Linux mint 21.1 Distro. You're my f*ckin hero dude, right after cryinkfly himself.

**Comment by monte-monte** [comment]
Spent half a day yesterday trying different things in bottles on Ubuntu to no success. Deleted and reinstalled everything from scratch. What mint has different for bottles and flatpak to work with this?!

**Comment by dumbnerd08** [comment]
Update to whoever can review and merge pull requests, this seems to work well as long as the wget command with the options in the install script in alextrical's repo is used. I could not find a source for the fusion installer anywhere other than wayback machine without downloading it and uploading it to somewhere like mega which would be extremely suspicious. I even contacted Autodesk about this issue and they weren't able to provide me with an older installer, so I think it is safe to merge this pull request #324.

**Comment by kcneato** [comment]
> Can verfify that it works on a freshly installed Linux mint 21.1 Distro. You're my f*ckin hero dude, right after cryinkfly himself.

Can you please explain how you make the start script? I dont get one created by itself.

**Comment by dumbnerd08** [comment]
> > Can verfify that it works on a freshly installed Linux mint 21.1 Distro. You're my f*ckin hero dude, right after cryinkfly himself.
> 
> Can you please explain how you make the start script? I dont get one created by itself and when i try tro make it run i just get the "txt file already exists" error...

Try deleting the ~/.fusion360 folder then rebooting your machine and trying again. If that doesn't work, make sure your system is fully up to date. If that doesn't work, I don't know what to tell you.

**Pull request merged**
